<?php  if ( ! defined('ABSPATH')) exit('No direct script access allowed');

return array(
    'main_layout' => 'wide',
    'header_type' => 'xstore',
    'header_full_width' => '1',
    'fixed_header' => '1',
    'header_overlap' => '1',
    'header_color' => 'white',
    'shopping_cart_icon' => 1,
    'header_bg' =>
        array (
            'background-color' => ''
        ),
    'top_bar' => '1',
    'top_bar_bg' =>
        array (
            'background-color' => ''
        ),
    'top_bar_color' => 'white',
    'header_custom_block' => '',
    'logo' => '',
    'logo_fixed' => '',
    'logo_width' => '170',
    'top_links' => '1',
    'search_form' => '1',
    'top_panel' => '1',
    'breadcrumb_type' => 'default',
    'breadcrumb_size' => 'large',
    'breadcrumb_padding' => array(),
    'breadcrumb_effect' => 'mouse',
    'breadcrumb_bg' =>
        array (
            'background-color' => '#dc5958',
            'background-image' => 'http://8theme.com/import/xstore/wp-content/uploads/2016/05/breadcrumb-1.png',
        ),
    'breadcrumb_color' => 'white',
    'footer_columns' => '4',
    'footer_demo' => '1',
    'to_top' => '1',
    'to_top_mobile' => '1',
    'dark_styles' => '',
    'activecol' => '#d64444',
    'background_img' =>
        array (
            'background-color' => ''
        ),
    'container_bg' =>
        array (
            'color' => '',
            'alpha' => '',
            'rgba' => '0,0,0',
        ),
    'menu_align' => 'center',
     'bc_title_font' => 
      array (
        'font-family' => '',
        'font-options' => '',
        'google' => '1',
        'font-weight' => '',
        'font-style' => '',
        'subsets' => '',
        'text-transform' => '',
        'font-size' => '',
        'line-height' => '',
        'color' => '',
      ),
      'bc_breadcrumbs_font' => 
      array (
        'font-family' => '',
        'font-options' => '',
        'google' => '1',
        'font-weight' => '',
        'font-style' => '',
        'subsets' => '',
        'text-transform' => '',
        'font-size' => '',
        'line-height' => '',
      ),
      'bc_return_font' => 
      array (
        'font-family' => '',
        'font-options' => '',
        'google' => '1',
        'font-weight' => '',
        'font-style' => '',
        'subsets' => '',
        'text-transform' => '',
        'font-size' => '',
        'line-height' => '',
      ),
      'sfont' => 
      array (
        'font-family' => '',
        'font-options' => '',
        'google' => '1',
        'font-weight' => '',
        'font-style' => '',
        'subsets' => '',
        'text-transform' => '',
        'font-size' => '',
        'line-height' => '',
        'color' => '',
      ),
      'headings' => 
      array (
        'font-family' => '',
        'font-options' => '',
        'google' => '1',
        'font-weight' => '',
        'font-style' => '',
        'subsets' => '',
        'text-transform' => '',
        'line-height' => '',
        'color' => '',
      ),
      'menu_level_1' => 
      array (
        'font-family' => '',
        'font-options' => '',
        'google' => '1',
        'font-weight' => '',
        'font-style' => '',
        'subsets' => '',
        'text-transform' => '',
        'font-size' => '',
        'line-height' => '',
        'color' => '',
      ),
      'menu_level_2' => 
      array (
        'font-family' => '',
        'font-options' => '',
        'google' => '1',
        'font-weight' => '',
        'font-style' => '',
        'subsets' => '',
        'text-transform' => '',
        'font-size' => '',
        'line-height' => '',
        'color' => '',
      ),
      'menu_level_3' => 
      array (
        'font-family' => '',
        'font-options' => '',
        'google' => '1',
        'font-weight' => '',
        'font-style' => '',
        'subsets' => '',
        'text-transform' => '',
        'font-size' => '',
        'line-height' => '',
        'color' => '',
      ),
    'footer_color' => 'light',
    'footer-links' =>
        array (
            'regular' => '#bbbbbb',
            'hover' => '#ffffff',
            'active' => '',
        ),
    'footer_bg_color' =>
        array (
            'background-color' => ''
        ),
    'copyrights_color' => 'light',
    'copyrights-links' =>
        array (
            'regular' => '',
            'hover' => '',
            'active' => '',
        ),
    'copyrights_bg_color' =>
        array (
            'background-color' => ''
        ),
    'custom_css' => '',
    'cart_widget' => '1',
    'just_catalog' => '0',
    'top_toolbar' => '1',
    'filters_columns' => '3',
    'filter_opened' => '',
    'cats_accordion' => '1',
    'out_of_icon' => '1',
    'sale_icon' => '1',
    'product_bage_banner' => '',
    'cat_style' => 'default',
    'cat_text_color' => '',
    'cat_valign' => 'center',
    'view_mode' => 'grid_list',
    'prodcuts_per_row' => '3',
    'products_per_page' => '9',
    'grid_sidebar' => 'left',
    'shop_full_width' => '0',
    'product_img_hover' => 'swap',
    'product_view' => 'mask',
    'product_view_color' => 'dark',
    'product_page_productname' => '1',
    'product_page_cats' => '1',
    'product_page_price' => '1',
    'product_page_addtocart' => '0',
    'single_sidebar' => 'without',
    'single_layout' => 'default',
    'product_name_signle' => '0',
    'upsell_location' => 'sidebar',
    'show_related' => '1',
    'related_limit' => '10',
    'thumbs_slider' => '1',
    'product_posts_links' => '1',
    'share_icons' => '1',
    'tabs_type' => 'tabs-default',
    'tabs_location' => 'after_content',
    'reviews_position' => 'tabs',
    'product_link' => '1',
    'blog_layout' => 'default',
    'blog_columns' => '3',
    'blog_full_width' => '0',
    'blog_hover' => 'animated',
    'blog_byline' => '1',
    'read_more' => '1',
    'views_counter' => '1',
    'blog_sidebar' => 'right',
    'excerpt_length' => '25',
    'post_template' => 'default',
    'blog_featured_image' => '1',
    'post_share' => '1',
    'about_author' => '1',
    'posts_links' => '1',
    'post_related' => '1',
    'related_query' => 'categories',
    'portfolio_style' => 'default',
    'portfolio_fullwidth' => '0',
);
